config/routes.rb
Rails.application.routes.draw do
  get 'events/new'

  get 'events/show'

  root 'static_pages#home'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
	resources :users
	resources :events, only: [:index, :new, :create, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attended_event.rb
class AttendedEvent < ApplicationRecord
	belongs_to :attendee, class_name: "User"
	belongs_to :user_event, foreign_key: "event_id", class_name: "Event"
end

app/models/event.rb
class Event < ApplicationRecord
	belongs_to :creator, class_name: "User"
	has_many :attended_events, foreign_key: "event_id" 
	has_many :attendees, through: :attended_events, source: :attendee
	scope :upcoming, -> {where("event_date > ?", DateTime.now )}
	scope :previous, -> {where("event_date < ?", DateTime.now  )} 
end

app/models/user.rb
class User < ApplicationRecord
	EMAIL_FORMAT = /\A[a-z].+@[a-z]+.[a-z]+\z/
	has_many :events, foreign_key: "creator_id"
	has_many :attended_events, foreign_key: "attendee_id"
	has_many :user_events, through: :attended_events, source: :user_event
	before_save :email_downcase
	validates :name, presence: true
	validates :email, presence: true, 
						 format:{with: EMAIL_FORMAT},
						 confirmation: {case_sensitive: false}  
	def email_downcase
  	email.downcase!
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  def correct_user
  	redirect_to login_path unless is_logged_in? 
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	before_action :correct_user, only: [:new, :create]

	def index
		@events = Event.all
	end

  def new
  	@event = Event.new
  end

  def create 
  	@event = current_user.events.build(event_params)
  	if @event.save
  		flash[:success] = "Event created"
  		redirect_to @event
  	else
  		render :new
  	end
  end

  def show
  	@event = Event.find(params[:id])
  end

  private 

  def event_params
  	params.require(:event).permit(:event_date, :event_name, :event_description)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	@user = User.find_by(email: params[:session][:email])
  	if @user
  		log_in @user, params[:session][:remember_me]
  		redirect_to root_path
  	else
  		flash[:danger] = "No user with this email"
  		render :mew
  	end  
  end

  def destroy
  	log_out
  	redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :correct_user, only: [:show]

  def new
  	@user = User.new
  end

  def create 
  	@user = User.new(user_params)
  	if @user.save
  		redirect_to root_path
  	else
  		render :new
  	end
  end

  def show
  	@events = current_user.events 
 		@user = @events.first.creator
  end

  private

  def user_params
  	params.require(:user).permit(:name, :email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def log_in(user, remember_me = '0')
		if remember_me == '1'
			cookies.signed[:user_id] = user.id
			session[:user_id] = user.id
		else
			session[:user_id] = user.id
		end
	end 

	def current_user
		current_user ||= User.find_by(id: session[:user_id])
		if current_user
			current_user 
		else 
			current_user ||= User.find_by(id: cookies.signed[:user_id])
			if current_user
				log_in current_user
				current_user
			end
		end
	end

	def log_out
		cookies.delete(:user_id)
		session.delete(:user_id)
		current_user = nil
	end

	def is_logged_in?
		!current_user.nil?
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_event.html.erb
<h1><%= link_to event.creator.name, event.creator %></h1>
<h3><%= event.event_name%></h3>
<h3><%= event.event_date%></h3>
<h3><%= event.event_description%></h3>

app/views/events/index.html.erb
<h1>All events</h1>
<h1>Upcoming events</h1>
<%= render @events.upcoming %>
<h1>previous events</h1>
<%= render @events.previous %>

app/views/events/new.html.erb
<h1>New event</h1>
<%= form_for @event do |f| %>
	<%= f.label :event_date %>
	<%= f.date_field :event_date %>
	
	<%= f.label :event_name %>
	<%= f.text_field :event_name %>

	<%= f.label :event_description %>
	<%= f.text_area :event_description%>
	
	<%= f.submit "Create event"%>
<%end%>

app/views/events/show.html.erb
<h1><%= @event.event_name %></h1>
<p><%= @event.event_description %></p>

<h2>List of guests</h2>
<ul>
	<% @event.attendees.each do |attendee| %>
			<li><%= attendee.name %></li>	
	<%end%>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<header>
  	<% if is_logged_in? %>
      <%= link_to "Home", root_path %>
  		Hello, <%= current_user.name%>
  		<%= link_to "Log out", logout_path(current_user), method: :delete %>
      <%= link_to 'My events', user_path(current_user)  %>
      <%= link_to 'All Events', events_path %>
  	<%else%>
  		<%= link_to "Log in", login_path %>
      <%= link_to 'Sign up', new_user_path %>
  	<%end%>
  	</header>
    <%= yield %>
  </body>
</html>

app/views/static_pages/home.html.erb
<h1>This is your home page</h1>

app/views/users/new.html.erb
<h1>Sign up</h1>
<%= form_for @user do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name%>

	<%= f.label :email %>
	<%= f.email_field :email%>
	
	<%= f.submit "Sign up"%>
<%end%>

app/views/users/show.html.erb
<h1>Events</h1>

<h2><%= @user.name %></h2>
<h3>Events created</h3>
<ul>
	<% @events.each do |event| %>
		<li>
			<span> <%= event.event_date %> </span>
			<span> <%= link_to event.event_name, event %> </span>
			<span> <%= event.event_description %> </span>

		</li>
	<%end%>
</ul>

<%= link_to "New event", new_event_path %>

<h3>Upcoming Events</h3>

<ul>
	<% @user.user_events.upcoming.each do |event| %>
		<li>
			<span> <%= event.event_date %> </span>
			<span> <%= link_to event.event_name, event %> </span>
			<span> <%= event.event_description %> </span>

		</li>
	<%end%>
</ul>

<h3>Previous Events</h3>

<ul>
	<% @user.user_events.previous.each do |event| %>
		<li>
			<span> <%= event.event_date %> </span>
			<span> <%= link_to event.event_name, event %> </span>
			<span> <%= event.event_description %> </span>

		</li>
	<%end%>
</ul>